export const LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const LOGIN_ERROR = "AUTH_LOGIN_ERROR";
export const LOGOUT_SUCCESS = 'AUTH_LOGOUT_SUCCESS';
export const SIGNUP_SUCCESS = 'AUTH_SIGNUP_SUCCESS';
export const SIGNUP_ERROR = 'AUTH_SIGNUP_ERROR';

export const DISCLAIMER_ACCEPTED = "DISCLAIMER_ACCEPTED";
export const TOGGLE_DRAWER = "TOGGLE_DRAWER_OPEN";

export const ERROR_COMMUNICATING_WITH_SERVER = "ERROR_TALKING_TO_SERVER";